### ISSUE TITLE
The Smart Mirror lets me book an Uber, check emails, Facebook & Twitter

### ISSUE THREAD

**Issue by safaaelbrans** [prabhatsoni99/Smart-Magic-Mirror#1]
can you help me please  i need  the source code The Smart Mirror lets me book an Uber, check emails, Facebook & Twitter

**Comment by prabhatsoni99** [comment]
Hey @safaaelbrans you would need to use APIs of the above platforms.
Uber: https://developer.uber.com/docs/riders/ride-requests/tutorials/api/python
Twitter: https://stackabuse.com/accessing-the-twitter-api-with-python/
Facebook: https://pypi.org/project/python-facebook-api/
                  https://towardsdatascience.com/how-to-use-facebook-graph-api-and-extract-data-using-python-1839e19d6999
For checking Gmail body: https://developers.google.com/gmail/api/v1/reference

**Comment by prabhatsoni99** [comment]
@safaaelbrans didn't get a reply since some time! Assuming your query got solved.
